Revert "Add Component Report"
This reverts commit ee10052eb6388e1c220d509227b6455221836ef9.

There is an unexpected error when deploying.  Reverting for now to
unblock other devs.

    Traceback (most recent call last):
      File "/opt/rollingpin/rollingpin/deploy.py", line 140, in run_deploy
        code_host, [sync_command])
    TypeError: on_host_end() got an unexpected keyword argument 'results'
    *** deploy aborted: unexpected error in sync/build